name: Delete media-candidates branch
on: workflow_dispatch
permissions:
  contents: write
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - run: gh api -X DELETE "repos/${{ github.repository }}/git/refs/heads/media-candidates"
        env:
          GH_TOKEN: ${{ github.token }}
